version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webservice
file_exists_behavior: OVERWRITE
hooks:      
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 600
      runas: ec2-user

  ValidateService:
    - location: scripts/validateservice.sh
      timeout: 600
      runas: ec2-user